### ISSUE TITLE
.cmpthese borks with "Cannot resolve caller Numeric(Telemetry::Period: );"

### ISSUE THREAD

**Issue by Juerd** [tony-o/perl6-bench#13]
```
1;1 juerd@cxien:~$ perl6 -e 'use Bench; Bench.new.cmpthese: 1, { a => sub { }, b => sub { } }'
Benchmark: 
Timing 1 iterations of a, b...
         a: 0.000 wallclock secs (0.000 usr 0.000 sys 0.000 cpu)
		(warning: too few iterations for a reliable count)
         b: 0.000 wallclock secs (0.000 usr 0.000 sys 0.000 cpu) @ 16666.667/s (n=1)
		(warning: too few iterations for a reliable count)
Cannot resolve caller Numeric(Telemetry::Period: ); none of these signatures match:
    (Mu:U \v: *%_)
  in method cmpthese at /home/juerd/rakudo/install/share/perl6/site/sources/8E18DD7D6DD0C726C19B637ABDB3666A9B2327BC (Bench) line 192
  in block <unit> at -e line 1
```

**Comment by tony-o** [comment]
This issue should be fixed (should no longer error out).  Telemetry is giving me wild numbers on running empty subs though, so either this module needs an overhaul or my computer is doing something funny, curious what your results are -

**Comment by 0racle** [comment]
I'd also add that this issue is only fixed when providing `cmpthese` with a positive integer (for iterations).

Providing a negative integer (for seconds) still cannot resolve the caller.

```
% perl6 -e 'use Bench; Bench.new.cmpthese: -3, { a => sub { }, b => sub { } }'
Benchmark: 
Running a, b, for at least 3 seconds...
Cannot resolve caller Real(Telemetry::Period:D: ); none of these signatures match:
    (Mu:U \v: *%_)
  in method countit at ... (Bench) line 107
  in method timethis at ... (Bench) line 152
  in method timethese at ... (Bench) line 182
  in method cmpthese at ... (Bench) line 188
```
On a related note, when using seconds (with `:no-telemetry`), I guess it uses that value as the iteration count, and reports too few iterations, even when there are well over 10000 iterations.

```
Benchmark: 
Running fast, slow, for at least 3 seconds...
      fast: 3.110 wallclock secs @ 242246.555/s (n=753423)
                (warning: too few iterations for a reliable count)
```

**Comment by tony-o** [comment]
@0racle - thank you for bringing this up.  This module needs an overhaul.  I'm going to push a fix for this bug later today, i see the issue but not an good way to fix it with telemetry.

**Comment by tony-o** [comment]
@0racle @Juerd testing a rewrite and a fix for this type of issue with #14
